### ISSUE TITLE
Pokedex 902 Basculegion is missing in data

### ISSUE THREAD

**Issue by chaeyoon1101** [pokemon-go-api/pokemon-go-api#64]
- https://pokemon-go-api.github.io/pokemon-go-api/api/pokedex.json

Pokedex 902 Basculegion is missing

**Comment by mario6700-pogo** [comment]
hey,
this repository use the data from the Pokemon GO gamedata. And currently Basculegion isn't available yet
https://pokemongo.fandom.com/wiki/Basculegion#Availability

I think and hope as soon as we get Basculegion in pokemon go it should also available here

**Comment by chaeyoon1101** [comment]
Ahh.. that’s right

Thank you for providing such a useful API service
